config/routes.rb
Rails.application.routes.draw do
 get '/accounts/delete'
 post '/accounts/delete'
 devise_for :users
 get '/mis_publicacions' => 'publications#mis_publicacions'
 get '/statistics/por_post'
 post '/statistics/por_post'
 get '/statistics/publication_search'
 post '/statistics/publication_search'
 
 root 'publications#index'
 
 get '/orden=:string' => 'publications#filtro' , as: :filtro
 get '/publications' => 'publications#index' , as: :inicio
 get '/categorias=:string' => 'publications#categorias', as: :categoria
  resources :publications do
    resources :questions, :only => [:create, :update]
    resources :offers, :only => [:create]
    get '/:ganador' => 'publications#elegir_ganador', as: :elegir_ganador
  end

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	belongs_to :user
	has_many :questions
	has_many :offers

  validates_presence_of :name, :description
  validates :image, :format => URI::regexp(%w(http https))

	scope :recientes, -> { order("created_at desc")}
  
  scope :a_z, -> { order("name")}
  scope :z_a, -> { order("name desc")}

  scope :venc_prox, -> { order("expiration")}
  scope :venc_lejano, -> { order("expiration desc")}
  scope :activas, lambda { where("expiration > '#{Time.now}'") }
  scope :inactivas, lambda { where(" '#{Time.now}' > expiration") }
  scope :finalizadas, lambda { where("finished = ?", true) }
  scope :en_curso, lambda { where("finished = ?", false) }

  def self.con_id(id)
    # where(:title, query) -> This would return an exact match of the query
    where("id = ?", id)
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(name) like ? OR lower(description) like ?", "%#{query}%".downcase, "%#{query}%".downcase)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	def new
    @publicacion = Publication.new
  end

  def create
    @publicacion = Publication.new()
    @publicacion.user_id = current_user.id
    @publicacion.name= publicacion_params[:name]
    @publicacion.description= publicacion_params[:description]
    @publicacion.image= publicacion_params[:image]
    @publicacion.category= publicacion_params[:category]
    @publicacion.expiration= Time.now+ publicacion_params[:expiration].to_i.days
    if @publicacion.save
      redirect_to :action => "show", :id => @publicacion.id
    else
      render "new"
    end
  end

  def index
  	if params[:search]
      	@p = Publication.activas.search(params[:search]).order("created_at desc")
        if @p.blank?
          render 'no_resultados'
        end
    else
    	@p = Publication.activas.order("created_at desc")
    end
  end
  	
  def show
    @prod = Publication.find(params[:id])
    if (current_user.nil? == false)
      @nooferte = @prod.offers.where("user_id = ?", current_user.id).blank?
      @mioferta= @prod.offers.where("user_id = ?", current_user.id)
    end
  end
  
  def categorias
    @cat = Publication.activas.where("category LIKE :categoria", {:categoria => params[:string]})
  end

  def filtro
    @parametro = params[:string]

    case @parametro
      when 'AZ'
        @p = Publication.activas.a_z
      when 'ZA'
        @p = Publication.activas.z_a
      when 'Recientes'
        @p = Publication.activas.recientes
      when 'Venc_prox'
        @p = Publication.activas.venc_prox
      when 'Venc_lej'
        @p = Publication.activas.venc_lejano
      else
        redirect_to :back
    end
  end

  def mis_publicacions
    if current_user
      @p = current_user.publications
      if @p.blank?
        render 'no_resultados'
      end
    else
      redirect_to new_user_session_path, notice: 'No has iniciado Sesion'
    end
  end

  def elegir_ganador
    @prod = Publication.find(params[:publication_id])
    @prod.finished = true
    @oferta = Offer.find(params[:ganador])
    @prod.winner_id = @oferta.user_id
    @prod.terminated_date = Time.now
    @prod.save
    ActionCorreo.winner_email(@prod)
    redirect_to :back
  end

private
  def publicacion_params
    params.require(:publication).permit(:name, :description, :image, :category, :expiration)
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_filtro.html.erb
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Filtrar por
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-menu-right" role="menu" style="text-align: right">
    <li><a role="menuitem" href="<%= filtro_path('AZ')%>">A-Z</a></li>
    <li><a role="menuitem" href="<%= filtro_path('ZA')%>">Z-A</a></li>
    <li><a role="menuitem" href="<%= filtro_path('Recientes')%>">Fecha</a></li>
    <li><a role="menuitem" href="<%= filtro_path('Venc_prox')%>">Proximos Vencimientos</a></li>
    <li><a role="menuitem" href="<%= filtro_path('Venc_lej')%>">Vencimientos más lejanos</a></li>
  </ul>
</div>

app/views/publications/_menu_categorias.html.erb
<div class="panel panel-default titulo-categorias">
    <div class="panel-heading">
        <h5 class="panel-title"><b >Categorias</b></h5>
    </div>

        <ul class="list-group" >
            <a href="<%= categoria_path('Comestibles') %>" class="list-group-item" style="outline: medium none;
    border: 0px none" >Comestibles</a>
            <a href="<%= categoria_path('Deportes') %>" class="list-group-item">Deportes</a>
            <a href="<%= categoria_path('Electrodomesticos') %>" class="list-group-item">Electrodomésticos</a>
            <a href="<%= categoria_path('Electronica') %>" class="list-group-item">Electrónica</a>
            <a href="<%= categoria_path('Indumentaria') %>" class="list-group-item">Indumentaria</a>
            <a href="<%= categoria_path('Inmuebles') %>" class="list-group-item">Inmuebles</a>
            <a href="<%= categoria_path('Muebles') %>" class="list-group-item">Muebles</a>
            <a href="<%= categoria_path('Joyeria') %>" class="list-group-item">Joyería</a>
            <a href="<%= categoria_path('Vehiculos') %>" class="list-group-item">Vehículos</a>
            <a href="<%= categoria_path('Otros') %>" class="list-group-item">Otros</a>  
        </ul>
</div>

app/views/publications/_menu_usuario.html.erb
<div class="panel panel-default titulo-categorias">
	<div class="panel-heading">
		<h5 class="panel-title"><b >¡Bienvenido <%= current_user.name.humanize %>!</b></h5>
	</div>
	<ul class="list-group" >
		<a href="<%= edit_user_registration_path %>" class="list-group-item">Editar Perfil</a>
    <a href="<%= mis_publicacions_path %>" class="list-group-item">Mis Publicaciones</a>
		<a href="<%= new_publication_path %>" class="list-group-item">Nueva Publicacion</a>
    <% if current_user.admin %>
    <a href="<%= statistics_por_post_path %>" class="list-group-item">Estadísticas</a> 
    <%end%>
	</ul>
</div>

app/views/publications/_new_publication_form.html.erb
<%= simple_form_for @publicacion, url:{action:"create"} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, autofocus: true, required: true, label: "Titulo de la Publicacion", placeholder: 'Titulo' %>
    <%= f.input :description, label: "Descripcion", required: true, input_html: { style:'resize:none', size: "100x9"}, resizable: false, placeholder: 'Descripcion' %>
    <%= f.input :image, label: "Link a Imagen", required: true, placeholder: 'Link de imagen' %>
    <%= f.input :category, label: 'Elija la categoria del producto', collection: [ "Comestibles", "Deportes", "Electrodomesticos", "Electrónica", "Indumentaria", "Inmuebles", "Muebles", "Joyeria", "Vehiculos", "Otros"], :selected => 'Otros' %>
    <%= f.input :expiration, collection: 15..30, label: 'Duracion de la subasta', :selected => '15' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Publicar" %>
  </div>
<% end %>

app/views/publications/_orden.html.erb
<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
    Ordenar por
    <span class="caret"></span>
  </button>
  <ul id="sorts" class="dropdown-menu" role="menu">
    <li><a class="wrapTxt" role="menuitem" data-sort-value="name">A-Z<span class="mask"></span></a></li>
    <li><a class="wrapTxt" role="menuitem" data-sort-value="name_inv">Z-A<span class="mask"></span></a></li>
    <li><a class="wrapTxt" role="menuitem" data-sort-value="date">Más recientes<span class="mask"></span></a></li>
    <li><a class="wrapTxt" role="menuitem" data-sort-value="date_inv">Más antiguos<span class="mask"></span></a></li>
    <li><a class="wrapTxt" role="menuitem" data-sort-value="expiration">Próximos vencimientos<span class="mask"></span></a></li>
    <li><a class="wrapTxt" role="menuitem" data-sort-value="expiration_inv">Vencimientos más lejanos<span class="mask"></span></a></li>
  </ul>
</div>

app/views/publications/_publication.html.erb
<a href="<%= publication_path(pub) %>" class="item">
	  <div class="thumbnail">
	    <%= image_tag pub.image, :alt =>pub.name, :title =>pub.name %>
	    <div class="caption">
	      <h5 class="name"><b><%= pub.name %></b></h5>
	      <div><h6><%= pub.description.truncate(60,separator: ' ') %></h6></div>
         <p hidden class="date" ><%= pub.created_at.strftime("%d/%m/%y") %></p> 
	      <h6> Vence el: <span class="expiration"><%= pub.expiration.strftime("%d/%m/%y") %></span></h6>
	    </div>
	  </div>
</a>

<!-- size: '260x190' ,-->

app/views/publications/categorias.html.erb
<body class="fondo">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <%= render 'orden' %>
      </div>
      <div class="col-md-4" style="text-align: right">
        <%= render 'filtro' %>
      </div>
    </div>
    
    <br>

    <div class="row">
      <div class="col-md-2">
        <%= render 'menu_categorias' %>
      </div>

      <div class="col-md-8">
        <% if @cat.size == 0 %>
        <div class="no_producto">
          <h3 style="text-align: center">No hay productos en esta categoría.</h3>
        </div>
        <% end %>
        <div id="container" class="js-isotope" data-isotope-options='{ "itemSelector": ".item", "getSortData": { "name": ".name", "category": "[data-category]" } }'>
          <div class="ordenador">
            <%@cat.all.each do |pub| %>
            <%= render "publication",pub: pub %>
            <% end %>
          </div>
        </div>
      </div>
      


      <div class="col-md-2">
        <% if user_signed_in? %>
        <%= render "menu_usuario"%>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/publications/filtro.html.erb
<body class="fondo">

      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4 col-md-offset-2">
            <%= render 'orden' %>
          </div>
          <div class="col-md-4" style="text-align: right">
            <%= render 'filtro' %>
          </div>
        </div>

        <br>
        
        <div class="row">
          <div class="col-md-2">
            <%= render 'menu_categorias' %>
          </div>
          <div class="col-md-8">
            <div class="row row-centered ">
              <div class="col-md-12 col-centered">
                <div id="container" class="js-isotope" data-isotope-options='{ "itemSelector": ".item", "getSortData": { "name": ".name", "category": "[data-category]" } }'>
                  <div class="ordenador">
                    <%@p.all.each do |pub| %>
                    <%= render "publication",pub: pub %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-2">
            <% if user_signed_in? %>
            <%= render "menu_usuario"%>
            <% end %>
          </div>
        </div>

      </div>
    </body>

app/views/publications/index.html.erb
<body class="fondo">
  <script type="text/javascript" src="application.js"></script>
  


  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <%= render 'orden' %>
      </div>
      <div class="col-md-4" style="text-align: right">
        <%= render 'filtro' %>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-md-2">
        <%= render 'menu_categorias' %>
      </div>
      <div class="col-md-8">
        <div class="row row-centered ">
          <div class="col-md-12 col-centered">
            <div id="container" class="js-isotope" data-isotope-options='{ "itemSelector": ".item", "getSortData": { "name": ".name", "category": "[data-category]" } }'>
              <div class="ordenador">
                <%@p.all.each do |pub| %>
                <%= render "publication",pub: pub %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <% if user_signed_in? %>
        <%= render "menu_usuario"%>
        <% end %>
      </div>

    </div>
  </div>


</body>

app/views/publications/mis_publicacions.html.erb
<body class="fondo">

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <%= render 'orden' %>
      </div>
    </div>

    <br>
    <div class="row">
      <div class="col-md-2">
        <%= render 'menu_categorias' %>
      </div>
      <div class="col-md-8">
        <div class="row row-centered ">
          <div class="col-md-12 col-centered">
            <h2 style="text-align: center">Mis publicaciones</h2>
            <h3>Publicaciones en curso</h3>
            <div id="container" class="js-isotope" data-isotope-options='{ "itemSelector": ".item", "getSortData": { "name": ".name", "category": "[data-category]" } }'>
              <div class="ordenador">
                <%@p.activas.all.each do |pub| %>
                <%= render "publication",pub: pub %>
                <% end %>
              </div>
            </div>
            <h3>Publicaciones vencidas</h3>
            <div id="container" class="js-isotope" data-isotope-options='{ "itemSelector": ".item", "getSortData": { "name": ".name", "category": "[data-category]" } }'>
              <div class="ordenador">
                <%@p.inactivas.en_curso.all.each do |pub| %>
                <%= render "publication",pub: pub %>
                <% end %>
              </div>
            </div>
            <h3>Publicaciones finalizadas</h3>
            <div id="container" class="js-isotope" data-isotope-options='{ "itemSelector": ".item", "getSortData": { "name": ".name", "category": "[data-category]" } }'>
              <div class="ordenador">
                <%@p.finalizadas.each do |pub| %>
                <%= render "publication",pub: pub %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <% if user_signed_in? %>
        <%= render "menu_usuario"%>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/publications/new.html.erb
<div class="container-fluid master-container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-primary">
        <div class="panel-heading">Crear publicación</div>
        <div class="panel-body">
          <%= render partial: 'new_publication_form'%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publications/no_resultados.html.erb
<body class="fondo">

  <div class="container-fluid">
    <!-- Categorias/Lista/Nada -->
    <div class="row cat_list_bann">
        <div class="col-md-2">
          <%= render 'menu_categorias' %>
        </div>

        <div class="col-md-8 lista_index">
          <div class="no_producto">
            <h3 style="text-align: center">No se encontraron resultados para su busqueda.</h3>
          </div>
        </div>

        <div class="col-md-2">
            <% if user_signed_in? %>
             <%= render "menu_usuario"%>
            <% end %>
        </div>
    </div>
   </div>
</body>

app/views/publications/show.html.erb
<body class="fondo">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel bestnid-primary">
          <div class="panel-heading">
            <h3><%= @prod.name %> </h3>
          </div>
          <div class="panel-body">
            <div class="col-md-7">
              <div class="well">
                <%= image_tag @prod.image, size: '350x300' ,:alt => @prod.name, :title => @prod.name %>
              </div>
            </div>
            <div class="col-md-5 ">
              <div class="well well-lg">
                <%= @prod.description %>
              </div>
            </div>
          </div>
          <div class="panel-footer">
            <div class="row">
              <div class="col-md-6">
                Fecha de publicación: <%= @prod.created_at.strftime("%d %b %y") %>
              </div>
              <div class="col-md-6" style="text-align: right">
                Fecha de vencimiento: <%= @prod.expiration.strftime("%d %b %y") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default widget">
          <div class="panel-heading">
            <h3 class="panel-title"> Comentarios</h3>
          </div>
          <div class="panel-body">
            <ul class="list-group">
              <% if @prod.questions.blank? %>
              <li class="list-group-item">
                <p>Aún no hay consultas en esta publicación</p>
              </li>
              <% else %>
              <%@prod.questions.each do |c| %>
              <li class="list-group-item">
                <div class="row">
                  <%= render partial: "forms/question_question", locals: {consult: c} %>
                  <% if user_signed_in? %>
                      <% if ((current_user.id == @prod.user_id) and (c.answer.blank?) and (Publication.inactivas.con_id(@prod.id).blank?)) %>
                          <%= render partial: "forms/answer_form", locals: {consult: c} %>
                      <%end%>
                  <%end%>
                  <%= render partial: "forms/question_answer", locals: {consult: c} %>
                </div>
              </li>
              <%end%>
              <%end%>
              <% if user_signed_in? %>
              <% if current_user.id != @prod.user_id %>
              <li class="list-group-item">
                <div class="row">
                  <%= render partial: "forms/question_form", locals: {publicacion: @prod} %>  
                </div>
              </li>
              <%end%>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% if user_signed_in? %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default widget">
          <% if current_user.id == @prod.user_id %>
          <div class="panel-heading">
            <h3 class="panel-title">
              Ofertas que te hicieron</h3>
            </div>
            <div class="panel-body">
              <ul class="list-group">
                <% if @prod.offers.blank? %>
                <li class="list-group-item">
                  <p>Aún no hay ofertas en tu publicación</p>
                </li>
                <%else%>
                <%@prod.offers.each do |p| %>
                <li class="list-group-item">
                  <div class="row">
                    <div class="col-xs-10 col-md-12">
                      <div class="list-group-item pregunta">
                        <p><b>Necesidad: </b><%= p.necessity %> </p>
                        <p><b>Monto (AR$): </b><%= number_with_precision(p.amount, :precision => 2) %></p>
                        <div class="row">
                          <div class="col-md-10">
                            <div class="mic-info-pregunta">
                              <%= p.created_at.strftime("%d %b %y") %>
                            </div>
                            <%aux= Publication.activas.con_id(@prod.id)%>
                            <% if !@prod.finished and aux.blank? %>
                            <div class="btn btn-default">
                              <%= link_to "Elegir ganadora", publication_elegir_ganador_path(p.publication,p) %>
                            </div>
                            <%end%>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <% end %>
                <%end%>
              </ul>
            </div>
            <% elsif @nooferte %>
            <div class="panel-heading">
              <h3 class="panel-title">Haz tu oferta</h3>
            </div>
            <div class="panel-body">
              <ul class="list-group">
                <!--li class="list-group-item"-->
                <div class="row">
                      <%= render partial: "forms/new_offer_form", locals: {publicacion: @prod} %>  
                </div>
                <!--/li-->
              </ul>
            </div>
            <%else%>
            <div class="panel-heading">
              <h3 class="panel-title">¡Ya hiciste tu oferta!</h3>
            </div>
            <div class="panel-body">
              <ul class="list-group">
                <li class="list-group-item pregunta" style="word-wrap: break-word">
                  <div class="row">
                    <div class="col-xs-10 col-md-12">
                        <%@mioferta.each do |o| %>
                        <p><b>Necesidad: </b><%= o.necessity %> </p>
                        <p><b>Monto (AR$): </b><%= number_with_precision(o.amount, :precision => 2) %></p>
                        <%end%>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
            <% end %>
          </div>
        </div>
      </div>  
      <%end%>  
    </div>
  </body>