config/routes.rb
Rails.application.routes.draw do
 get '/accounts/delete'
 post '/accounts/delete'
 devise_for :users
 get '/mis_publicacions' => 'publications#mis_publicacions'
 get '/statistics/por_post'
 post '/statistics/por_post'
 get '/statistics/publication_search'
 post '/statistics/publication_search'
 
 root 'publications#index'
 
 get '/orden=:string' => 'publications#filtro' , as: :filtro
 get '/publications' => 'publications#index' , as: :inicio
 get '/categorias=:string' => 'publications#categorias', as: :categoria
  resources :publications do
    resources :questions, :only => [:create, :update]
    resources :offers, :only => [:create]
    get '/:ganador' => 'publications#elegir_ganador', as: :elegir_ganador
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

  <div class="container-fluid ">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, :method => 'get', class: 'navbar-brand' do %>
      <%= image_tag "https://dl.dropboxusercontent.com/u/97561407/logo.png", title: 'Logo', class: 'logo'  %>
      <% end %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(publications_path, :method => "get", class: "navbar-form navbar-left", id: "search-form") do %>

      <div class="form-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Ingrese busqueda" %>
        <button class="btn btn-default" type="submit">Buscar</button>
      </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
        <li><%= link_to current_user.name.humanize,root_path %></li>
        
        <li><%= link_to "Cerrar sesion", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to 'Iniciar sesion',new_user_session_path%></li> 
        <li><a href="<%=new_user_registration_path %>">Registrarse</a></li> 
        <% end %>

        
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" type="image/png" href="https://dl.dropboxusercontent.com/u/97561407/favicon.ico"/>
  <title>Bestnid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <br>
    <br>

    <div id="principal">
    <% flash.each do |key, value| %>
      <% if key == "alert" %>

        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert">x</button>
          <%=value %>
        </div>

      <% else %>
        
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert">x</button>
          <%=value %>
        </div>

      <% end %>
    <% end %>

    <%= yield %>
    
    </div>
    
  </body>
</html>